### ISSUE TITLE
Ghostwriter 2.0.1 doesn't recognize theme

### ISSUE THREAD

**Issue by ghost** [dracula/ghostwriter#1]
It seems after getting to version 2.0.1 of ghostwriter this theme doesn't work.

inxi output:

> `CPU: Quad Core AMD Phenom II X4 810 (-MCP-) speed/min/max: 1900/800/2600 MHz 
Kernel: 5.12.9-1-MANJARO x86_64 Up: 4d 1h 22m Mem: 5744.5/16009.8 MiB (35.9%) 
Storage: 7.74 TiB (51.4% used) Procs: 274 Shell: fish inxi: 3.3.04`

Screenshots:

![Screenshot_2021-06-19_17-10-06](https://user-images.githubusercontent.com/19254816/122656640-15d05480-d122-11eb-9543-a8bee760f9cd.png)
![Screenshot_2021-06-19_17-08-39](https://user-images.githubusercontent.com/19254816/122656637-110ba080-d122-11eb-9129-1f254d14fa3f.png)

**Comment by ghost** [comment]
It appears after creating my own, they use JSON now in this format (Still storing the json file in `~/.config/ghostwriter/themes/[theme].json` ). In this case `dracula.json`.

This is the one I've come up with so far:

```
{
    "dark": {
        "accent": "#bd93f9",
        "background": "#282a36",
        "block": "#ffb86c",
        "cursor": "#44475a",
        "emphasis": "#f1fa8c",
        "error": "#ff5555",
        "foreground": "#f8f8f2",
        "heading": "#ff79c6",
        "link": "#8be9fd",
        "markup": "#50f97b",
        "selection": "#44475a"
    },
    "light": {
        "accent": "#bd93f9",
        "background": "#282a36",
        "block": "#ffb86c",
        "cursor": "#44475a",
        "emphasis": "#f1fa8c",
        "error": "#ff5555",
        "foreground": "#f8f8f2",
        "heading": "#ff79c6",
        "link": "#8be9fd",
        "markup": "#50f97b",
        "selection": "#44475a"
    }
}
```

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
I can confirm that the original theme does not work on a `fedora34` box with `ghostwriter 2.0.2` either.

However, using the current instructions, I was equally as unable to make it work with the JSON one that you put together @GregTheHun , placing it in `~/.config/ghostwriter/themes/dracula/theme.cfg` (I even tried renaming it to `.json` there) - ghostwriter simply doesn't see anything from the themes' subdirs.

What *did* work for me was placing a `<theme-name>.json` (i.e. `dracula.json`, `.cfg` didn't work) directly in the `~/.config/ghostwriter/themes` directory.

**Comment by totoroot** [comment]
@GregTheHun Sorry for the late response. I do not use ghostwriter often anymore. The update to 2.0.0 broke the compatibility of this theme with ghostwriter as the theming system got completely redesigned.

I just updated the theme with PR #3. Please check if this works for you.

@wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf I also updated the [installation instructions](https://github.com/dracula/ghostwriter/blob/master/INSTALL.md), so please take a look at them as long as the [Dracula Theme website](https://draculatheme.com/ghostwriter) has not yet been updated.

If you're still having problems installing the theme please just ping me here.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> @GregTheHun Sorry for the late response. I do not use ghostwriter often anymore. The update to 2.0.0 broke the compatibility of this theme with ghostwriter as the theming system got completely redesigned.
> 
> I just updated the theme with PR #3. Please check if this works for you.
> 
> @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf I also updated the [installation instructions](https://github.com/dracula/ghostwriter/blob/master/INSTALL.md), so please take a look at them as long as the [Dracula Theme website](https://draculatheme.com/ghostwriter) has not yet been updated.
> 
> If you're still having problems installing the theme please just ping me here.

hey, thanks for the update.
in the meanwhile (`fedora 35` + `ghostwriter 2.1.0`) I have been using a manually added Dracula colorscheme.
I can confirm that having `Dracula.json` in `~/.config/ghostwriter/themes` (I even have it symlinked from the folder where I have the repo cloned and I kept up to date) shows an option in the app (as per installation instructions), both the dark and the light mode work.

**Comment by totoroot** [comment]
Thanks for your response! Glad you made it work in the meantime.
I'm going to close this issue then.
